# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
            ],
        ),
    ]
