# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Content', models.CharField(max_length=120)),
                ('Time', models.CharField(max_length=120)),
            ],
        ),
    ]
