# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminders',
            old_name='Title',
            new_name='title',
        ),
    ]
