# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20160326_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminders',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='Time',
            new_name='time',
        ),
    ]
