# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='category',
        ),
    ]
