# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Description',
            new_name='description',
        ),
    ]
