# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20160326_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='deleted',
            field=models.TextField(default='false'),
            preserve_default=False,
        ),
    ]
